name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        pip install flake8
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: slnyvlqp
        postgresql user: slnyvlqp
        postgresql password: "VwR9nd-EDEi0e-GkeeetJltyH7Je43-y"

    - name: Django Test
      env:
        SECRET_KEY : x&fn-qus1+5e%@b88s1w#y7nwf25s-q*cfadf=7ym9r35zy#k*
        JWT_SECRET_KEY : JWT-SECRET_KEYJWT-SECRET_KEYJWT-SECRET_KEYJWT-SECRET_KEY
        DATABASE_URL : postgres://slnyvlqp:VwR9nd-EDEi0e-GkeeetJltyH7Je43-y@queenie.db.elephantsql.com:5432/slnyvlqp
      run: |
        python3 manage.py test


